import Foundation

// AUTO-GENERATED by build.sh — do not edit by hand.
public let kBuildStamp = "20260727085640-83e9e60"

/// Full daemon version: protocol + build stamp. Both parts must match.
public var kDaemonFullVersion: String { "\(kDaemonProtocolVersion)+\(kBuildStamp)" }
